spring:
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/lakeSide-hotel
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
